#!/bin/bash

repository="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
branch="gh-pages"
folder="doc/book"

git config --global user.name "gh-actions"
git config --global user.email "actions@github.com"

git clone --single-branch --branch "${branch}" "${repository}" tmp
mv tmp/.git "${folder}"/.git
rm -rf tmp

pushd "${folder}"

git add --all
git commit -m "Update"
git push "${repository}" HEAD:"${branch}"

popd
